### ISSUE TITLE
Refactor/redesign Protocol to consume itself

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#110]
The homepage for the protocol site should use our card designs. The individual component pages should use our article page templates.

**Comment by alexgibson** [comment]
@michaelmccombie curious is this something you're still working on? I was wondering if splitting out the component editor into a separate piece of work to the redesign might be a good idea.

**Comment by alexgibson** [comment]
I'm not sure if this is being worked on still, but it has been in development since last May!? 🙂 

@michaelmccombie what's the status here, is this something you're still working on? If you're being pulled to work on other things, perhaps we can scope this work out into smaller, actionable steps. I'm sure the devs would be happy to help with this work, if we can know what it encompasses?
