### ISSUE TITLE
Section with three columns

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#154]
**Variations**
- Text can be either center or left-aligned
- Background color should be interchangeable

**Desktop (1024px)**
<img width="504" alt="image" src="https://user-images.githubusercontent.com/5924575/41958819-09be2370-79a0-11e8-853a-fa82e90fd4c1.png">

**Mobile (480px)**
<img width="266" alt="image" src="https://user-images.githubusercontent.com/5924575/41958904-5763929a-79a0-11e8-9825-7fe9678695e2.png">

**Comment by alexgibson** [comment]
What I think I've settled on here is to make this a new variation of a card component as @michaelmccombie suggested. Because it shares little in common with a regular card however, it's likely not going to inherit all the base styles from a regular card, and instead use a base class of its own (e.g. `mzp-c-card-icon`) to avoid overriding properties it doesn't need.

For layout, we can still use `mzp-l-card-third` and `mzp-l-layout-card-half`, but those layout classes can have some specific rules for `mzp-c-card-icon` child elements.
