### ISSUE TITLE
Update Table Component

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#186]
We have a couple of upcoming projects that will need a data-table (user-friendly sitemap, the language selector page, careers.mozilla). This component already exists in ProgressUI (https://protocol.mozilla.org/patterns/atoms/typographic.html). It looks like there only a handful of small tweaks to make for the desktop version of this component. The mobile version needs some thought.

## Desktop
- 100% width
- Either remove border between rows or make it optional

## Mobile
- Make responsive using the "Collapse Rows" method
https://css-tricks.com/accessible-simple-responsive-tables/

![collapse](https://cdn.css-tricks.com/wp-content/uploads/2016/03/types-of-responsive-tables.gif)

## Related Tickets
https://github.com/mozilla/bedrock/issues/5827

![screen shot 2018-07-26 at 5 07 00 pm](https://user-images.githubusercontent.com/5924575/43294882-5ad7d612-90f6-11e8-8da0-1cdeb2872179.png)

**Comment by alexgibson** [comment]
I'm curious if a `<table>` is actually the most suitable form of markup here. This design looks more like a list with a heading to me, rather than somehting that represents tabular data.

Curious if any other front-enders have opinions here? /cc @craigcook @stephaniehobson @amychurchwell 

If a table isn't best suited here, this could be a case of something that may well only exist one one page, so doesn't need to be a protocol component yet (until we can justify it).

**Comment by stephaniehobson** [comment]
Agreed. This is a list.

**Comment by alexgibson** [comment]
Ok, I'm gonna say that https://github.com/mozilla/protocol/issues/186 no longer depends on this issue, and move forward with a simple heading / list. Until we have precedence of this particular styling pattern over multiple pages, I don't think it needs to be a component just yet.

**Comment by stephaniehobson** [comment]
Sounds like the use case this was opened to handle has been covered.
