### ISSUE TITLE
Naming conventions we'd like to revisit.

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#196]
Sometime after we've been using the system for a few months and before it starts getting used by projects other than bedrock we should review the names things have for changes we can make to standardize things.

Add comments to this issue for things we should consider at that time.

**Comment by stephaniehobson** [comment]
Should we standardize on `wrapper` vs `container`?

**Comment by alexgibson** [comment]
+1 for standardizing on `wrapper` vs `container`. I'd also love to find a nicer solution to `left` and `right`. Using `reverse` is definitely nicer, but in the case of the feature card the default orientation is vertical, so it doesn't quite work.

As for the definition of a card, I'm not sure if we've really decided what that is yet. It could be defined by a block link, or it could also mean anything that is a combo of an image/title/description. So far, we've been leaning toward the latter but this is still all up for discussion.

**Comment by craigcook** [comment]
We did bikeshed a bit around left/right/reverse but didn't reach a conclusion. I cringe a little at left/right mainly because I think the layout should probably flip in RTL... if something is `.mzp-l-right` does that mean it's ALWAYS on the right since the class is explicit, or do we flip it to the left for RTL, in which case the class is misleading?

I came up with "reverse" for the hero sections because it already had a `mzp-has-image` modifier to go from vertical to side-by-side... So for that component, no class is vertical, `.mzp-has-image` is left aligned, `has-image.mzp-l-reverse` is right aligned. Of course that won't work for all cases, like the feature card. I had also initially used `mzp-l-adjacent` as a generic "side by side instead of stacked" modifier that doesn't imply direction, then `reverse` as a further modifier to reverse the default. But at that point it starts to feel like we're avoiding directional names for philosophical reasons instead of practical.

So I hate to admit it, but I'm coming around on some limited use of pragmatically presentational names. These layout classes are already presentational so we might as well go all in and make them explicitly so. I'd be in favor of standardizing `mzp-l-left` and `mzp-l-right` and they can be reversed for RTL.

**Comment by stephaniehobson** [comment]
The `text-align` spec solved the left/right problem with `start` and `end`. (Start being left in LTR and right in RTL).

**Comment by stephaniehobson** [comment]
But... yeah, left and right is very clear.

**Comment by alexgibson** [comment]
Another one for discussion: standardize on what we mean by a "component".

Example: In the docs we use `atoms`, `molecules` and `organisms` to structure our patterns, yet in the source scss, everything is lumped under `/components`. We also seem to interchangably talk about components as opposed to molecules etc in the documentation. I think it would be less confusing if we stuck to one thing, and organised our files similarly.

**Comment by johngruen** [comment]
decisions:

* alignment should be: `start, end, reverse` and not `left, right, reverse`
* for components that describe things that are layered in some way, the outermost box should name the component, and an inner `-content` class should define the fill-able area eg
```
<div class="modal>
    <div class="modal-content">
```

**Comment by stephaniehobson** [comment]
Sounds good closing the discussion and opening an implementation issue: https://github.com/mozilla/protocol/issues/448
