### ISSUE TITLE
Page Hero inconsistencies between bedrock and protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#222]
During working on https://github.com/mozilla/bedrock/issues/6107 I noticed a few small inconsistencies between the hero sections on bedrock pages, and how they are definied in Protocol. We should figure out if we need to update the specs in Protocol to follow suit.

1. The [Chrome compare page](https://www.mozilla.org/en-US/firefox/new/?xv=chrome&v=2) features a [basic hero](https://protocol.mozilla.org/patterns/organisms/hero.html#hero), but contains an image below it. It omits using `mzp-has-image` to avoid floating the image, despite the section containing an image.

2. The [Pocket page hero](https://www.mozilla.org/en-US/firefox/pocket/) contains a Pocket wordmark inside the title as an inline `<img>`. We should probably have pocket built-in for this component, like we do for FIrefox but using a `mzp-t-product-pocket` class. This would require adding the Pocket logo to protocol-assets.

**Comment by craigcook** [comment]
I've been thinking of refactoring the hero component to use `left` and `right` classes instead of `has-image` and `reverse`. It wasn't originally designed for a centered image, but the comparison page deviated from the design. I considered putting that image outside the hero component (in the section after it) but, really, it's obviously a hero image. So I think we need to update the component with a centered image as the default (when there is an image) with left and right layout variations.

For Pocket, I think we should add a `product-pocket` brand variation to this and other components (and add the Pocket logo to our assets).

**Comment by maureenlholland** [comment]
closing as we have deprecated hero component
