### ISSUE TITLE
Create a style for centered headlines

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#235]
General headings get standard text alignment depending on the language direction (LTR or RTL). But some pages benefit from centered headings for section titles. We should create a reusable class for this treatment.

Simplest would be a global utility class like `.mzp-u-centered { text-align: center; }` but that's really presentational and I worry about misuse. I'm not opposed to limited utility classes I just don't want to make them so generic that they end up enabling bad habits. Classes should describe what an element is or what it does, not just what it looks like. Littering markup with lots of presentational classes is hardly any better than inline styling.

A more restricted but also more meaningful approach would be an atom/component for "section titles" which can optionally be centered, e.g. `.mzp-c-section-title.mzp-u-centered { text-align: center; }` That at least says "this element is a section title, and it's also centered." But if we want to make this a new atom we'll need to think more about its use and styling.

**Comment by michaelmccombie** [comment]
@craigcook You make some good points about the misuse of utility classes and we should also be wary of creating classes for instance that are too specific. So there is definitely a happy medium that can be reached.

**Markup we want to avoid**
```
<h1 class="font-sans color-black size-lg style-underline alignment-center">This is a headline</h1>

<h1 class"heading-for-article-pages-about-security-that-include-video">This is a headline</h1>
```

As far as centering text goes I think that might be an instance were it's worth using a utility class because it is a commonly asked for modification that can be applied to multiple elements within multiple components. (headings, paragraphs, images, links, etc.).

**Comment by craigcook** [comment]
Yeah, I just don't want people to use `class="mzp-u-centered"` in HTML every single time they really just want `text-align: center;` in CSS. The utility class should be a rarity. We can discourage abuse of presentational classes in our docs but in the hands of real people who knows what they might do. Hence my fear of enabling bad habits simply by providing the tools. It's the "guns don't kill people" argument: technically correct, but if that person didn't *have* a gun...

And yet, I don't want to create a whole component only to justify centering the occasional headline. But maybe we can think it through and decide this really is an atom we want to standardize as a "section title" or whatever we call it. Something to bikeshed about.

**Comment by alexgibson** [comment]
Perhaps we don't need a utility class for this, and heading alignment could be dictated by the parent layout class? e.g. single condensed column layouts have centered headings. 

Just a random thought.

**Comment by michaelmccombie** [comment]
Maybe we should use this as an opportunity to rethink the way we theme pages. At the moment we have one theme `mzp-t-firefox` which is being referenced twice in our source code.

```
.mzp-t-firefox {
    h1, h2, h3, h4 {
        @include open-sans;
    }
}
```
```
.mzp-c-hero.mzp-t-firefox {
        &:after {
            ...
            mask: url('#{$image-path}/backgrounds/masks/hero/hero-curve.svg') center bottom no-repeat;
            ...
        }
```

This feels just a little bit clunky because you could have a page where the Firefox theme is being applied to the `main` tag and again within the hero tag. 

```
<main class="mzp-t-firefox">
    <div class="mzp-c-hero mzp-t-firefox">...</div>
</main>
```
The `mzp-t-firefox` class name can also be applied as a utility class of sorts if you apply it to a heading's container.
```
<span class="mzp-t-firefox"><h1>This is a Headline</h1></span>
<span class="mzp-t-firefox"><h2>This is a sub-heading</h2></span>

```
The `mzp-t-firefox` tag is also being applied to pages like /pocket which call for sans-serif headlines but the content isn't specific to Firefox.

So I think a simpler approach would be to make our themes something that can only be applied once on a page by tying them to the 'main' tag. This would avoid some of our concerns with abusing presentational classes and give us some added flexibility.

```
main {
    h1, h2, h3, h4, blockquote {
        @include sans;
        text-align: left;
    }
}
main.mzp-t-serif {
    h1, h2, h3, h4, blockquote {
        @include serif;
    }
}
main.mzp-t-center {
    h1, h2, h3, h4, blockquote {
        text-align: center;
    }
}
.mzp-c-hero.mzp-has-wave {
        &:after {
            ...
            mask: url('#{$image-path}/backgrounds/masks/hero/hero-curve.svg') center bottom no-repeat;
            ...
        }
}

**Comment by craigcook** [comment]
Closing in favor of #664 which will address this use case with a proper component.
