### ISSUE TITLE
Naming Conventions for IDs/Aria-Controls 

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#243]
There is an "id" being used on the menu page, `#mzp-c-menu-panel-example`, for aria controls. 
In the nav demo that class changes to `#mzp-c-menu-panel-firefox`, `#mzp-c-menu-panel-about`, etc.

We don't explain that the id needs updating on the "Menu" page. So we should add that to the notes section for that component. https://protocol.mozilla.org/patterns/molecules/menu.html

Also we should think about how we name id's. `#mzp-c-menu-panel-example` is pretty close to how we name our CSS classes. Maybe we could drop the namespace and go with something like `#menu-panel-example` or we could go with `#mzp-aria-menu-panel-example` which we do for classes that are targeted with javascript. Or we could leave it the way it is.

**Comment by stephaniehobson** [comment]
I agree we should drop the `mzp-c-`.  IDs should be unique, they are not part of the component.

I'm less confident the right direction to go with adding a new prefix. I'd lean more towards a `js-` prefix than an `aria-` one because we will always need js to go with the aria and then we don't have to do mental gymnastics to figure out which name to use. But I'm not sure we need a prefix for IDs.
