### ISSUE TITLE
Create new atomic heading sizes

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#297]
Protocol already has a good set of default heading sizes, but at the component level we override those defaults using component-specific classes:

- `mzp-c-call-out-title`
- `mzp-c-card-feature-title`
- `mzp-c-card-title`
- `mzp-c-hero-title`
- `mzp-c-billboard-title`
- `mzp-c-card-picto-title`
- `mzp-c-article-title`
- `mzp-c-newsletter-title`
- `mzp-c-card-feature-title`

In practical use this has turned out to be too limiting. Designs often require setting different visual heading sizes depending on the hierarchy of the content, and we're also rewriting a lot of the same CSS for each component which is inefficient.

It may be more flexible to have a set of generic heading style classes e.g.

- `mzp-u-title-xs`
- `mzp-u-title-sm`
- `mzp-u-title-md`
- `mzp-u-title-lg`
- `mzp-u-title-xl`

Components could then use these generic classes as needed, and it would also be easy to swap out for a new class if a heading needed a slightly different visual hierarchy.

In addition, headings could also come with some sort of `mzp-has-icon` modifier, which enables incorporating an icon as a pseudo element, as seen in the Call Out and Hero components.

**Comment by craigcook** [comment]
Since these classes are presentational I would suggest a `u-` prefix instead of `c-`.

Alternatively, I've been thinking along the lines of a small set of universal title classes and let the size be determined by their context. Like `mzp-c-title-primary` and `mzp-c-title-secondary` or similar. Basically treating a "title" as a standalone component with some default styling applied to ALL such titles, then the presentation can be refined for different contexts.

Something like:

`.mzp-c-article .mzp-title-primary { @include text-display-xl; }`
`.mzp-c-card .mzp-title-primary { @include text-display-sm; }`

But I'm probably being a semantic purist and I should just accept that presentational utility classes are super useful and pragmatic, and I'll just die a little bit more inside every time I use one.

**Comment by alexgibson** [comment]
https://twitter.com/csswizardry/status/1093083909468889088

**Comment by stephaniehobson** [comment]
Can we safely assume titles should be the appropriate brand font?

**Comment by stephaniehobson** [comment]
McDonald's option for discussion:

https://github.com/mozilla/protocol/pull/387/files

```
mzp-u-title-xxl {
    @include text-display-xxl;

    .mzp-t-mozilla {
        & {
            @include font-mozilla;
        }
    }

    .mzp-t-firefox {
        & {
            @include font-firefox;
        }
    }
}
```

**Comment by stephaniehobson** [comment]
Now that I'm looking at it I really want to alias `@mixin text-display-lg` to `@mixin text-title-lg`. Would that increase or decrease confusion and muscle memory?

**Comment by mheubusch** [comment]
@stephaniehobson Is this issue done from a developer perspective? If so, it is ok to close. Craig and I talked about how we can close things so they get out of the developer's queue and keep them in the documentation column until I can review and add information for any design guidelines. Thank you!

**Comment by stephaniehobson** [comment]
Yes, the code work is done.
