### ISSUE TITLE
Licence should be MPL 2.0

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#30]
The current license in the repo is MIT, but we should move this over to MPL 2.0?

**Comment by craigcook** [comment]
The MIT license came from Drizzle, and I'm not sure of the implications of changing a license. At what point can we say this is no longer "a fork of Drizzle" and is actually new original software "inspired by Drizzle"? The separate dependencies have their own licenses so that's not an issue, it's just the framework that stitches them together we'd be licensing. We've rewritten pretty large chunks of it by now, maybe there's not much of the original left.

**Comment by alexgibson** [comment]
Hmm yeah, I was forgetting this is a fork. I’m not sure where that leaves us tbh. Maybe we will have to keep the original MIT licence.
