### ISSUE TITLE
Refactor/replace Picto card component

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#382]
The upcoming designs for /new and /thanks feature some changes to the Picto card component that are not currently part of the design component spec:

- Larger icon sizes. The current Picto card component features 56x56px icons, but the new designs feature larger icons at arbitrary sizes. I suggest we add an option for incorporating a larger icon size, but agree to a set size.
- The /thanks page features a row of 4 Picto cards, but our current layout options support only 3.

**Comment by stephaniehobson** [comment]
Can we update it to allow a <img src="" alt="" role="presentation"> of arbitrary size? (Constrained by the width of the column). Then we don't have to write custom CSS for these every time.

I think the picto card should be an molecule and the 4 column grid should be separate from content inside it. (Though maybe that is too big a change to make to accommodate the use case presented here).

**Comment by amychurchwell** [comment]
Supports horizontal and vertical layout.

![Screen Shot 2019-07-17 at 11 00 24 AM](https://user-images.githubusercontent.com/30483988/61399132-57935900-a882-11e9-9c81-87a2a39f1407.png)

![Screen Shot 2019-07-17 at 11 02 28 AM](https://user-images.githubusercontent.com/30483988/61399154-67ab3880-a882-11e9-9e79-f8b5a4fe5a38.png)

**Comment by craigcook** [comment]
Jotting some notes as I've been working on refactoring this component...

I'm making it take an inline image as opposed to a CSS background on a pseudo-element, so that should simplify usage. The only problem I've run into with accepting arbitrary sizes is that it can result in uneven heights across a row. I think that's probably best avoided by just using the same height images within a given set of cards, which seems better than trying to prescribe image heights within the component itself.

The newer WNP design has the icons on top, so for now I'm building this to *always* have images above content. If we later want to create an image-on-the-side variant we can deal with that when it comes.

I'm also defaulting to inherited alignment with the image aligned with the text (so aligned left in LTR and aligned right in RTL), and `.mzp-t-align-center` as a theme option.

**Comment by stephaniehobson** [comment]
Do we have existing image-on-the-side implementations we need to accommodate or are you suggesting we drop support for those?

**Comment by stephaniehobson** [comment]
Also... do we even need a component for "an image with some text underneath it"? What's different about that than an `<img>` followed by a `<p>` tag?

**Comment by alexgibson** [comment]
I have no strong feelings on updating vs deprecating this component. If we were to deprecate it then we should flesh out the atomic level & layout changes needed to replace it, as it’s currently used in quite a few places. I do think this type of element appears throughout our pages enough to warrant having something that helps creating this in a low effort and consistent way.

**Comment by craigcook** [comment]
After simmering on the back burner for a long time this has evolved into a new component to replace the existing picto card, addressing the issues above, including a multi-column layout container. It will address #384 and #443 as well.
