### ISSUE TITLE
Update type scale(s)

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#410]
On https://protocol.mozilla.org/fundamentals/typography.html please update to show Custom Headings that are taken from the Brand Guidelines, in addition to showing default. 

**All are in Metropolis Bold**

- Display XXL - Font Size, 64px (4rem), Line Height 72px
- Display XL - 56px (3.5 rem), Line height 64px
- Display LG - Font Size - 48px (3rem), Line Height, 56px
- Display MD - 40px (2.5rem), Line Height - 44px
- Display SM - 32px (2rem), Line height - 36px
- Display XS - 24px (1.5rem), Line height: 28px

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

**Comment by craigcook** [comment]
All of these sizes are already in Protocol, or is this just about updating the line heights? Current Protocol uses a 1.1 line-height for all headings whereas the brand guide rounds them to the nearest multiple of four. Protocol used to do that same rounding before we simplified it, but we can bring it back.

**Comment by wboucherfischer** [comment]
We have the default headings (h1, h2, h3, h4, h5, h6), but we had talked about custom heading classes to call. I think those should be defined and on this page. So if somebody wants to make an h1 smaller, etc. I think a 1.1 line height is fine.

**Comment by craigcook** [comment]
PR #387 relates to this (which in turn references issue #297)

But I think we might need to discuss the line height thing further and try to reach consensus, and probably separately from this issue. I'll file another issue for that.

**Comment by craigcook** [comment]
Rambling thoughts incoming.

So... most of what we've been talking about in relation to atomic headings is only regarding the sizing, which we already do with mixins. We can make any element any size with a line of CSS, with no further effort required.

We can instead create a set of presentational utility classes (as in #387 ), so we could arbitrarily size elements in HTML without writing custom CSS for it, but that upsets my purist sensibilities so I'd like to avoid that. Using classes for sizing means we use HTML to describe appearance. We could make pages without ever writing any page-level CSS, but I'm not sure that's actually a good goal. Sizing a heading with a utlity class instead of a mixin isn't really turning it into an "atomic component", it's just a shortcut to avoid writing new CSS. If we have to write HTML to specify a size, I'm not sure `class="mzp-u-display-xl;"` is any better than `style="font-size: 2rem;"`.

Instead I'd like to discuss defining a few *kinds* of headings, like page titles, main titles, sub titles, section titles, block titles, whatever we end up calling them... but we can look at a bunch of pages with a bunch of different headings and see if we can describe the purpose of those headings and arrive at some general categories based on what they do, not just what they look like. Once we know what kind of heading it is, *then* we can design what it looks like.

For example, a page title. We know what that is: it's the title of the page, it's at the top, it's usually big, it's usually an h1, there should be only one of them per page. We can decide what all our page titles will look like, and make that an atom called `.mzp-c-page-title` with usage guidelines. That's an atomic component that we can drop into any number of molecules or organisms and maintain some consistency across all our page titles. 

And there could be a handful of variants. Maybe sometimes they're centered, sometimes they're left aligned, sometimes they have a logo above them, sometimes they're paired with a tagline, etc etc... Sometimes the variant will depend on the context in which it's used... maybe it's XXL when it's the title of a landing page and XL when it's the title of an article. It could be one component that comes in a few flavors, but lots of ways to use it, and it would always be internally consistent because we've designed it intentionally. We wouldn't have a dozen pages with a dozen different page titles because they were each designed as one-offs without no relation to any other page. The power of systems!

What do we think?

**Comment by stephaniehobson** [comment]
Rambling reactions :)

I am against having a class that behaves differently in different components. The advantage of using classes over relying on the cascade is knowing exactly how they will behave and they lose that if they behave differently in different situations.

The ultimate utopia here is for the designers to articulate among themselves and come up with a limited set of font size and colour combinations they will use. That limited pallet then gets made into, not utility classes, but theme classes. Since we're essentially theming components.

Craig, unless the designers can articulate a chain of logic that is getting them to use a pink headline here and a purple one (and a pink AND purple one here) there it will be impossible for us to avoid utility/theme classes. I have not received designs where the designer has thought about what _kind_ of headline is which. The advantage of the utility classes is that we don't have to make a page specific style sheet (with all the maintenance over head, and extra HTTP request) just because this headline has two colours in it, in a different order from the last time a headline had two colours.

I think the difference between our two approaches is that I want to react to what is happening and make it faster to build and you want to change what is happening.

**Comment by craigcook** [comment]
> Craig, unless the designers can articulate a chain of logic that is getting them to use a pink headline here and a purple one (and a pink AND purple one here) there it will be impossible for us to avoid utility/theme classes. I have not received designs where the designer has thought about what _kind_ of headline is which. The advantage of the utility classes is that we don't have to make a page specific style sheet (with all the maintenance over head, and extra HTTP request) just because this headline has two colours in it, in a different order from the last time a headline had two colours.

> I think the difference between our two approaches is that I want to react to what is happening and make it faster to build and you want to change what is happening.

Correct, I want to make the designs better and more consistent, and I don't want to write code that enables bad design. Making a bunch of classes so devs can more easily implement bad designs does not make the designs better. It's solving the wrong problem.

**Comment by wboucherfischer** [comment]
If the default line height has been 1.1 rem, I think we are fine with continuing that.

I'm still not sure on having a new class for every simple atomic part of each component. I'm open to it, but the headings sizes for each component should still follow what is in the headings in the brand guidelines as with the paragraph body copy. 

From looking at atomic design systems, they just tend to have the headings, and then default to the various heading sizes for the component. That is why I was proposing that we have a set of custom heading font sizes based on the heading sizes in the Brand Guidelines. We only use those sizes in any web design that have been agreed upon by the marketing organization. Additionally after some discussion with Mark, Justin K, Carolyn and Michael H., we would have heading colors in:

White
Ink Purple
Pink
Orange
Red
(other color?) and potentially also have paragraph text too. 

The designers would like to be able to have some visual emphasis but the default text for headings would be the White and Ink purple and not be limited to White/Ink purple. However, we would have guidelines around when to use other colors and why. 

Sorry, I'm trying

**Comment by craigcook** [comment]
> I'm still not sure on having a new class for every simple atomic part of each component. I'm open to it, but the headings sizes for each component should still follow what is in the headings in the brand guidelines as with the paragraph body copy.
> 
> From looking at atomic design systems, they just tend to have the headings, and then default to the various heading sizes for the component. That is why I was proposing that we have a set of custom heading font sizes based on the heading sizes in the Brand Guidelines. We only use those sizes in any web design that have been agreed upon by the marketing organization. 

We have that type scale defined already and we use Sass mixins to apply sizing to an element. A sizing class in HTML would just be an alias for one of those Sass mixins, and then the class is strictly presentational markup. `<h3 class="text-display-xl">` doesn't tell me what kind of h3 it is, what it contains, where it belongs, or what purpose it serves, it only tells me how big it is. I know I'm being a stickler for semantic markup and separating content from presentation, and maybe I'm just old fashioned. But I'm so far unconvinced that sizing classes would make life better for anyone.

The use case here seems to be "designers keep sizing things willy nilly and devs have to write snowflake CSS to achieve it, so we should make presentational classes so the devs can size things willy nilly by writing HTML instead of CSS." My proposed solution to that problem is "designers shouldn't size things willy nilly."

I know that's easy for me to say, but I feel it's the better solution. Treating the symptom might bring temporary comfort, but it doesn't cure the disease.

**Comment by wboucherfischer** [comment]
But I talked to the designers and they say they use the sizes that are in
the brand guidelines. And the headings are based on the size in the brand
guidelines. They don't deviate from that. Do you have an example?

**Comment by craigcook** [comment]
The guidelines for the Mozilla brand have a completely different type scale for headings in Zilla Slab. We need to figure out how best to approach maintaining different type scales for different brands.

**Comment by craigcook** [comment]
> But I talked to the designers and they say they use the sizes that are in the brand guidelines. And the headings are based on the size in the brand guidelines. They don't deviate from that. Do you have an example?

Sorry, I think we're talking about two different things in the same thread and it's crossing over.

Designers are selecting sizes from the standard scale, but aren't always using the same size for the same object. Going back to our imaginary "page title" component, we might get a mockup where the page title is set in Display XL, and we might another mockup on another page at another time from another designer where the page title is set in Display LG. Designers are choosing sizes from the list, but they're not using them consistently based on the component at hand. They're sizing willy nilly based on how it looks on in a particular place, not what it IS.

I want to think about what it IS, and design modular components that look the same wherever they occur. A designer shouldn't just be choosing text from the predefined set of sizes, they should be using a component where the size has already been chosen.

**Comment by wboucherfischer** [comment]
Something must be getting lost in the process here. If there is a predefined stencil in the Protocol library, the designer can't change the font size or the sizing. Then the designers are locked into the sizing.

**Comment by dzingeek** [comment]
Sorry just now catching up on this convo (I am sure I am missing something)...The one main thing I care about is flexibility. There should be options for headlines anywhere on the page. 

_Example: Headline in the hero might be short so the headline can be larger (XXL) but for another page it might be longer so it might need to be smaller (XL)._

**Comment by craigcook** [comment]
> Sorry just now catching up on this convo (I am sure I am missing something)...The one main thing I care about is flexibility. There should be options for headlines anywhere on the page.
> 
> _Example: Headline in the hero might be short so the headline can be larger (XXL) but for another page it might be longer so it might need to be smaller (XL)._

OK, and that's what I'm arguing against. That's sizing text arbitrarily to look a certain way in a certain place with certain content. A design system is intended to avoid that kind of inconsistency.

If we need to expand our palette slightly so we have a handful variants, that's fine. We can make "Page hero with large title" and "Page hero with slightly smaller title" or whatever. But I want to think through those options, design them deliberately, and limit the number so they're consistent, not just provide a million variations so nothing looks the same anywhere.

**Comment by craigcook** [comment]
Even better, a "page title" atom that comes in two sizes, with guidelines around when to use which variant. Ideally those guidelines should be about how the text functions or what purpose it serves, not just how many characters there are since we don't always have control over that. Some rules about "use large titles on landing pages, small titles on subpages" or something like that. We should think about the entire system, not just one page at a time.

**Comment by dzingeek** [comment]
So I get what you are saying but I am pushing back a bit. While this is a design system it's not a product it's a marketing website so we need flexibility. We also need to let designers do their job and make calls based on visual elements and not be held back by "sorry you can only use 53px font for that." And yes while agree, I don't want the designers to character count (that was meant as an example and maybe not the best) and then pick a text size based on the characters, I do want them to be able to choose different sizes based on the impact they are trying to make. 

Could we not just say here are headline options (XXL, XL, LG...) you can use any of those but nothing outside of that unless you absolutely have a good reason?

**Comment by justinkropp** [comment]
I see the merits of both approaches. From the above thread, and other conversations I've read or have been a part  of it seems like one of the big areas where things have a tendency to "flex" a little more are the hero sections of our marketing pages. `Font-size` and image placement in these hero sections do tend to vary depending on the purpose of the page, and I don't really see the need for flexibility in this particular component changing that much in the future. 

The rest of the page(s) will typically consist of similar elements: cards, billboards, details, etc. Perhaps what we need the most flexibility in is:

1. the hero section layout
2. the overall layout of the page

I think what we want at the end of the day is as much consistency as possible while still maintaining a level of flexibility that gives the designers the tools to make every page as impactful as possible. 

We're still working through further refining the brand guidelines as well as expanding our protocol Sketch library based on those guidelines. 

For what it's worth @craigcook , I don't think you're old fashioned for wanting to adhere to semantic markup, but we may need to blur the lines of content and presentation from time to time. However, we're trying to mitigate the risk of that as much as possible with the development of our protocol Sketch library.

**Comment by craigcook** [comment]
> Could we not just say here are headline options (XXL, XL, LG...) you can use any of those but nothing outside of that unless you absolutely have a good reason?

That's pretty much exactly what I've been getting at. I'm in favor of a limited set of theme variants for a given component. I don't think this needs to be complicated, and I don't even think we're really in disagreement, I just keep failing to explain myself adequately. 

This is where design and code overlap and I'm trying to make us all happy. I just don't want loads of presentational markup, and I don't want every page to be a snowflake.

**Comment by ejregithub** [comment]
@craigcook - if you can size this independently, please do - and apply the Estimate.

**Comment by ejregithub** [comment]
@craigcook - please size this work, apply the Estimate and tag it with the Priority, P1, P2, P3 assigned by Justin.

**Comment by johngruen** [comment]
When implementing the type-scale, please cascade sizes off of a root class per #447

**Comment by johngruen** [comment]
Let's do this:
1. within the `mzp-t-usage-presentation` class (#447) we should set h{n} element selectors to match the rules Wendy defined above.
2. We should also have a set of utility classes within this namespace for `mzp-u-display-${size}
