### ISSUE TITLE
Add Firefox themed text input [forms]

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#430]
See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

Normal Text Input | Default text input
-- | --
Text Input, Hover | When user hovers over text box, a hover displays.
Text Input, Focus | When the user has selected the text box, a focus selection appears.
Text Input, Error | When there is an error in the text box element, an error state shows.
Text Input, Success | When the user is successful in enter an item in a text box, a success state shows.
Text Input, Disabled | There is a disabled state for the text box.

![text-input](https://user-images.githubusercontent.com/50332473/61409660-8e279e80-a897-11e9-911f-1892f75f5310.png)

**Comment by dzingeek** [comment]
Here are the visual specs
![input-field-specs](https://user-images.githubusercontent.com/3740746/67119316-c0e57980-f19b-11e9-91c0-6f941f8c3e6d.png)

**Comment by dzingeek** [comment]
@stephaniehobson here are the icons for the input fields (check, alert, down arrow...)
[input-field-icons.zip](https://github.com/mozilla/protocol/files/3795333/input-field-icons.zip)

**Comment by dzingeek** [comment]
**Here is an update to the error state**
![input field specs](https://user-images.githubusercontent.com/3740746/69278357-016b5500-0b97-11ea-86f1-b6aafbc67b49.png)

**Comment by dzingeek** [comment]
Just realized I didn't spec out the box shadow

[**.elevation-02** {](https://github.com/mozilla/protocol/issues/456)
  box-shadow: 0 16px 24px  2px hsla(261, 50%, 13%, .04),
              0 6px  32px  4px hsla(220, 79%, 17%, .12),
              0 8px  12px -5px hsla(261, 50%, 13%, .12);

**Comment by craigcook** [comment]
> Just realized I didn't spec out the box shadow
> 
> [**.elevation-02** {](https://github.com/mozilla/protocol/issues/456)
> box-shadow: 0 16px 24px 2px hsla(261, 50%, 13%, .04),
> 0 6px 32px 4px hsla(220, 79%, 17%, .12),
> 0 8px 12px -5px hsla(261, 50%, 13%, .12);

That shadow looks like this:
![image](https://user-images.githubusercontent.com/205591/69284487-970ce180-0ba3-11ea-8f80-7f41e5604bc5.png)

Is this for the little floating error messages? If so, that's a pretty heavy shadow for such a small element. They might look better with the smaller shadow (assigned the token `$box-shadow-sm` in https://github.com/mozilla/protocol-tokens/pull/66) and even that might be too much. I wonder if we need an even smaller shadow for things like this, or they might look best with no shadow at all.

Also the little arrow tip might not combine well with a shadow, since the box would cast a shadow but the arrow would not (depending on how we do the arrow). I think we can try it a few ways and see what looks right.

**Comment by dzingeek** [comment]
I thought that was the small shadow...nice catch @craigcook, yeah that is too much.. this might be something we can play around with in development to find the right fit then document it.
