### ISSUE TITLE
Create a Local Instance of Protocol Error

### ISSUE THREAD

**Issue by RyanWils** [mozilla/protocol#501]
Hi, I am on a **Windows environment** 

When I try to Npm Start, LintJS gives me an error 
Error: Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
![image](https://user-images.githubusercontent.com/49354833/66158065-1eea5c80-e5f3-11e9-8454-409ae6561e1a.png)

### Steps to reproduce
I have followed the instructions on Github and the Documentation, both seem to produce the same error

![image](https://user-images.githubusercontent.com/49354833/66157972-e5195600-e5f2-11e9-8ddf-cc2676fc4974.png)
![image](https://user-images.githubusercontent.com/49354833/66158098-332e5980-e5f3-11e9-88c6-99d80b11c644.png)

I have tried many different shells including CMD, Git Bash, and the integrated terminal on VS Code, changed the .gitattributes with ***.js text eol=lf**
None of these methods solved this error.

**Comment by Errolyn** [comment]
Thanks for reporting! Could you let us know what version of Node.js you have installed?

**Comment by RyanWils** [comment]
I have a fairly old version of Node.js, my version is v10.7.0.
I will try to update my Node.js to see if that's the issue.

**Comment by Errolyn** [comment]
Hi @RyanWils I think I have figured out a temp solution. I want to check with my team before deciding on how we are going to handle this in a more permanent manner. 

If you add 
```
"rules": {
        "linebreak-style": 0,
    }
```

to `protocol\gulpfile.js\.eslintrc.js` and `protocol\.eslintrc.js` files you should be able to run the server. NOTE: You will need to be running Node version: v10.16.3

**Comment by Errolyn** [comment]
@craigcook @amychurchwell  do you think we need to continue checking for linebreak styles, could it cause an issue if we don't? If not I can just add that rule to files and call it good?

**Comment by alexgibson** [comment]
@RyanWils so I believe we default to 'LF' style line breaks because that's the standard for Unix/Linux systems, and is fairly common default for a lot of open source GitHub projects. Still, if you're using Windows I think you can configure your code editor to use LF instead of CRLF (which is the default on Windows).

In the root of this project, there's an [`.editorconfig`](https://github.com/mozilla/protocol/blob/master/.editorconfig) file that can be used to help configure your code editor. If you install the [editorconfig plugin](https://editorconfig.org/) then it should help enforce things like LF line breaks for you. I believe you can also configure Git to do the same when checking code in/out.

Note that if you've already created some CRLF line breaks, you may need to fix those before linting will pass.

**Comment by craigcook** [comment]
We've switched to a new platform (Fractal) so the dependencies and setup have changed. This may no longer be relevant.
