### ISSUE TITLE
Investigate an alternate image replacement technique

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#519]
## Description

See: https://github.com/mozilla/bedrock/issues/8084

Safari has issues with Protocols current `image-replaced` mixin under certain circumstances.

Perhaps we should investigate utilizing a new method for this technique. This article has some options, but there may well be others: https://css-tricks.com/css-image-replacement/

**Comment by stephaniehobson** [comment]
I think the problem is that when a large `text-indent` value is supplied Safari dutifully tries to honour it. To do so the element would have to be huge, so the grid flexes to try to accommodate the huge element. Setting a specific width also fixes it (unfortunately `100%` doesn't count).

I think the easiest fix is to go even more old school to `text-indent: -9999px`;

I would like to switch to the height:0;padding-top method but unfortunately that would be a breaking change (and it really doesn't work with the close button on the notification bar).
