### ISSUE TITLE
Using the Zap component throws an error

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#520]
## Description

As reported by @sgarrity, the new "Zap" scss lives in the `/components/` folder, but trying to load it like other components throws an error, since it's actually available via a mixin and has a different relative path.

### Steps to reproduce

Try and import the Zap like other componentsusing e.g. 

```
@import '../../protocol/css/components/zap';
```

### Expected result

The component CSS should load.

### Actual result

Sass throws a compile error:

```
File to import not found or unreadable: ../protocol/includes/lib.
```

### Environment

N/A

**Comment by sgarrity** [comment]
For a bit of further context here, I'm looking to use the Zaps on the new browser comparison page (https://github.com/mozilla/bedrock/issues/7575).

I started by trying to include the component styles with the `@import '../../protocol/css/components/zap';` Alex mentioned above. I assumed this was way to include the styles based on similar components like `hero`.

I was then using this method of calling the styles:
```<h1 class="mzp-has-zap-1">Here is a zap <strong>one</strong> example.</h1>```

However, the `@import '../../protocol/css/components/zap';` throws an error. It appears that the `lib` path from the zap component scss file differs from other components. Is this intentional? 

For example:  
`_zap.scss` includes `@import '../protocol/includes/lib';` but  
`_hero.scss` includes `@import '../includes/lib';`

I am able to use the zap() mixin directly, but not the `.mzp-has-zap-1` class.

Let me know if I can provide any further detail that might help clarify.

**Comment by alexgibson** [comment]
> I am able to use the zap() mixin directly, but not the .mzp-has-zap-1 class.

Ah ok so that makes sense why this is in /components/, There's already a separate mixin. This may just be a case of fixing the import path, but I'll defer to @stephaniehobson here.
