### ISSUE TITLE
Figure out how to distribute theming

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/protocol#563]
Because we use Sass/SCSS mixins to render some of our brand-specific elements (font stack, type scale, color scheme) we need to determine a method for distributing themes in a way that projects can consume. This could be two separate NPM packages or it could be two bundles of mixins in the single package.

Figuring this out will take some tinkering and evaluation to choose the best approach.

There's a related question around mixing brands on a single page; e.g. a Mozilla box on a Firefox page or vice versa. We could decide just to forbid brand mixing, but that may be impractical. Assuming it's allowed we should establish some guidelines for when/how to mix brands responsibly, and that could factor into our theming mechanism.

**Comment by craigcook** [comment]
I entered into this expecting it to be two NPM packages and the task was to figure out how to accomplish that, or to determine it couldn't be done and find an alternative. So as far as I can tell each NPM package has exactly one git repository, so to fork the package we'd have to fork the Protocol repo and I definitely to NOT want to do that. The entire point of theming is to have one design system supporting two brands, not two design systems. I briefly looked into the feasibility of somehow managing two NPM packages from one repo but I'm not sure it's possible, or if it is, it might be really hacky. So publishing two packages is out because I think it would be a real pain to keep them in sync.

I also looked into a more old-school method where all the themed styles are dependent on a class, where the only thing you'd need to do to switch themes is swap a class in the HTML. That works, but results in a lot of duplicated and redundant CSS being generated. It places an unfair burden on the user to unwittingly download a lot of styling they don't need, just in case the developer might want it (and they usually won't).

So in the end, Protocol will continue to be a single NPM package that will ship with two branded themes, and it will be up to the developer implementing it to select a theme when they compile from source.

I'm not sure what this means for offering a pre-compiled CSS framework. I'm going to tinker a bit with somehow double-compiling during the build process, but I don't have high hopes for that working. We can still provide a pre-compiled Protocol with a default theme but I think anyone wanting to use the other one will need to do their own SCSS compiling.

We also discussed brand mixing, specifically whether it should be built in or explicitly forbidden. The consensus is that, while we may not be able to forbid it, it's very strongly discouraged. A Firefox-branded page should not feature any Mozilla-branded elements and vice versa; one brand per page, please. Thus we're not going to jump through hoops in Protocol to make brand-mixing easy to do. There may be rare exceptions to the rule and those exceptions will be one-off treatments where the developer will need to override an element's theme styling. This will all be documented when theming finally lands in Protocol.

There's more work to finish implementing brand themes in Protocol but this task was specifically just to figure out distribution, and I think I've figured that out so I'm calling this done.
