### ISSUE TITLE
Font stacks being wrapped in parentheses when compiling in Node Sass

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#653]
## Description

The team working on https://github.com/mozilla/glean-dictionary ran into a Sass compilation error using the Node Sass package (https://www.npmjs.com/package/sass). Font stacks are being enclosed in parentheses for some reason, which throws a "not valid CSS" error and compilation fails. Other compilers don't do this so it may be some particular syntax/configuration option with Node.

**Comment by Iinh** [comment]
A belated update: we (the Glean Dictionary team) were able to compile Protocol using [node-sass](https://www.npmjs.com/package/node-sass) instead of `sass`. However, this solution is not ideal as node-sass is deprecated. 

We're planning on upgrading our app to use a better frontend framework [SvelteKit](https://kit.svelte.dev/docs), but there is a blocker. [Vite](https://vitejs.dev/), the build tool that powers SvelteKit under the hood, [uses `sass` as its css preprocessor](https://vitejs.dev/guide/features.html#css-pre-processors), which makes it impossible to work with Protocol. 

I'm wondering if there's any plan to fix this bug soon, as we would love to continue using Protocol in our project. Also, being able to use sass to compile Protocol would make this design system even more accessible, as `sass` is a very popular compiler. Thank you!

cc/ @wlach
