### ISSUE TITLE
Add the ability to stage/demo work in progress

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#7]
Would be nice if we could spin up a short-lived demo instance based on a PR or branch for testing and review before something gets merged to master. I believe netlify can do this?

**Comment by craigcook** [comment]
CC @pmac

**Comment by pmac** [comment]
I believe this is now setup. Builds were failing due to the repo name change so I've also fixed that, but the site is at a different URL:

https://mozilla-protocol.netlify.com/

I've added deployment notifications to the slack channel, so pushing to any branch should build a and deploy and I believe the notification should include the URL. Test it out and let me know.

**Comment by craigcook** [comment]
Woo!

**Comment by alexgibson** [comment]
I've set deploys for: `master`, `demo1`, `demo2`, `demo3`.
