### ISSUE TITLE
Sass update: migrate away from @import

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/protocol#755]
## Description

Sass's target date to drop support for `@import` is [Oct. 2022](https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline)***. The Sass team has a [blog post on their reasoning for this.](https://sass-lang.com/blog/the-module-system-is-launched). We can use their migration tool, but there will likely be some manual restructuring/troubleshooting required.

***update July 2022: this target date has been postponed indefinitely, as the Sass team waits for greater migration to dart-sass

tl;dr:

- it was difficult to identify where “members” (variables, mixins, and functions) were set
- library authors struggled to manually namespace things to ensure they wouldn’t conflict with user names
- scope was unclear and could result in strange side effects

Miriam Suzanne has the best breakdown of this in my opinion, a [shorter primer on her site](https://www.oddbird.net/2019/10/02/sass-modules/) and a [longer CSS tricks article](https://css-tricks.com/introducing-sass-modules/).

If you want to see what this looks like in practice with bedrock, I opened an experimental branch and documented some errors I ran into: https://github.com/maureenlholland/bedrock/commit/bfa5cf1f789bd06731a7095461c4e17edee6b362#diff-8e07af2048c8e9d32f1610[…]1161183c678f0d2a9b67f517455

:warning: this messed with my mental model of sass and will definitely take some getting used to

## Success Criteria

- [ ] No `@import` statements in Sass
- [ ] Library still works as expected
- [ ] Any BREAKING CHANGES have migration tips in the changelog
- [ ] Docs are updated

**Comment by nathan-barrett** [comment]
hey @maureenlholland - been working on this slightly while you've been out - and it definitely will take some file restructuring in protocol some things to note:
- Looks like the depreciation has been pushed back: https://github.com/sass/sass/issues/3223#issuecomment-1002813284
- Peer modules arent supported (will throw an error) - so how we handle the `includes` folder will need to change since a lot of the functions, mixins, etc. are depending on eachother - https://github.com/sass/sass/issues/2774
- We should have specific entrypoints if were to move to the module system - currently as `sass-loader` understands our file structure - we have one in `themes` that imports from things in `assets` and that is causing issues when attempting to use ... `@use`

**Comment by maureenlholland** [comment]
Some thoughts for fixing the module loops we currently experience when running an automated sass migration:

1. Move user-configurable variables to a separate partial and `@forward` them in the lib file. (This would mean $brand-theme, $type-scale, $image-path, $fonts-path live in a separate `_config` partial, so it's clear users can change these variables when they load Protocol lib)

2. Move theme-specific functions to the themes partial. (`type-scale` and `get-theme` create loops between functions and themes partials, the idea here is to make functions theme-agnostic and create `theme` namespaced functions, i.e. `theme.type-scale` and `theme.get`)

3. Load base mixins (current `mixins.scss` file) and util mixins (everything in current `includes/mixins` folder) separately. (this is mostly to fix a loop from the border-box base mixin used in the grid util mixin, it loops when the grid mixin is loaded into the mixins file, but it also feels worth emphasizing the distinction between the mixins file, which has lots of low-level mixins, and the mixins folder, which has more high-level mixins)

Do any of these suggestions ring alarm bells? Or is it worth pursuing a demo of these changes?

**Comment by nathan-barrett** [comment]
Love all the thought and foresight you're putting into this @maureenlholland! I think the only bell that is ringing in my head with this, is that our documentation for protocol would need to be extra clear about how to import the different function and mixin files.

**Comment by craigcook** [comment]
I still haven't read up enough on `@use` so my opinions in this matter aren't well informed. Pardon me if I'm speaking from my own posterior.

1. I'm not opposed to having a `_config` file, and actually explored that at one point while working on theming. But what I ran into at the time was that with `@import` I had to set the theme variables _before_ importing `_lib` so all the bits can know what values to use when compiling, which meant every file had to import both `_config` and `_lib`, in that order, which felt too fragile to me so I didn't like it. Eventually I settled on just setting those variables in the main style sheet (and/or altering them per page, as long as they're before `_lib`). But if `@use` avoids that mess and we can make one `_config` file a sort of "set it and forget it" that still offers the chance to override those things on a per-page basis, then maybe option 1 can work. But I worry it would be similarly repetitive and fragile.

2. This makes sense to me. The only reason those functions are in `_functions` is because they're functions. Making them more theme-specific and rolling them up with the other theme stuff is logical, and based on my limited understanding of the problem this might be the simplest and most elegant solution.

3. This one also sounds potentially fragile, and might be a kind of hack to work around a particular quirk of our file organization rather than The Right Way To Do It.

So, given my poor comprehension, Option 2 sounds best to me. I'm prepared to be corrected.

**Comment by maureenlholland** [comment]
Thanks for the responses! For clarity, we would need to use all three of these suggestions or some variation of them because they are solving different loop issues.

For 3, we want to avoid the following loop:
- mixins.scss uses mixins/grid.scss
- mixins/grid.scss uses mixins.scss (to access the border-box mixin)

I think another, potentially less fragile way to do this is as follows:
- rename mixins.scss to base.scss (or any name we want) and move it into mixins folder
- add _index.scss to mixins folder
- mixins/_index.scss aggregates all the mixin partials (loads base and grid and everything else in that folder)
- no change to lib "mixins" load, because [sass automatically loads the _index.scss file at the folder name](https://sass-lang.com/documentation/at-rules/use#index-files)

For 1, we might need to do more thinking. The loop issue is:
- lib.scss uses functions.scss
- functions.scss uses lib.scss (for access to $brand-theme & $type-scale variables, this would be essentially the same loop if we move the type-scale and get-theme functions to themes.scss)

The current suggestion would (hopefully) work as follows:
```scss
/* _lib.scss */

@forward "config" /* when loaded, will use default config variable values unless other values are provided */

@use "other-stuff" /* any use of "config" within these modules should respect the values provided when the "lib" module is first used */
```

```scss
/* lib-firefox.scss */

@use "lib" with (
    $brand-theme: 'firefox',
    $font-path: '/firefox/fonts'
);

/* lib-mozilla.scss */

@use "lib" with (
    $brand-theme: 'mozilla',
    $font-path: '/mozilla/fonts'
);
```

```scss
/* pre-configured libs */

/* page-mozilla.scss */
@use "lib-mozilla" 

/* page-firefox.scss */
@use "lib-firefox"

/* file-specific config */

/* page-unbranded.scss */
@use "lib" with (
    $font-path: '/test/new/path/fonts'
);

/* file-specific config override*/

@use "lib-firefox"
lib-firefox.$image-path: '/test/images';
```

**Comment by craigcook** [comment]
Well I did warn you I didn't know what I was talking about. I read this as three solutions to one problem and I picked my favorite. But now that I know it's three problems...

1. One challenge is making Protocol easy to consume, and users should never be asked to edit a core file that will be overwritten by an update. If there is a single customer-edited config file that lives in the root that all other files can reference, that's easy. If there are multiple config files (e.g. one for each theme) then we should provide those and customers shouldn't edit them. Then a customer still needs to choose a theme/config, so that's no different from asking them to set variables at the top of a style sheet like we do now. So that can work too.

2. This is the one I understood best anyway, and it still makes the most sense, so let's do it. We'll move the functions around to solve the loop. 

3. If it's only a problem with the grid mixins... well we barely use the grid mixins anyway, so what if we just... don't? Replace the handful of references with a simple width instead of a mixin and kill off the grid mixins entirely. They're already underused and misunderstood, why do more work to preserve something we don't really need? (It was a different time, very early in Protocol dev and I was adamantly against a full-blown Bootstrap-style class-based grid system [still am], but still wanted to define some standards for column widths... they were never followed). Problem 3 solved.

**Comment by maureenlholland** [comment]
re: removing grid mixins - sounds good to me!

**Comment by craigcook** [comment]
That said, removing the grid mixins would be a breaking change (but so is all the rest of this stuff) so we'll need to do it with caution and offer some clear migration steps for anyone else who might be relying on them. If that seems to be too much hassle we could still break up mixins, which might be a good thing to do even beyond just fixing the grid looping problem.

**Comment by maureenlholland** [comment]
+1 on being extra careful with breaking changes (migration steps in changelog, doc updates... will update description for those success criteria)

re: config files, there might be something interesting we could do with allowing user-created themes, when folks want to use Protocol components, but with a theme not officially supported in the design system. Some Sass docs on `@use` and [style configuration through mixins](https://sass-lang.com/documentation/at-rules/use#with-mixins) might be worth a look.

**Comment by craigcook** [comment]
Done in https://github.com/mozilla/protocol/commit/d272e0be9dbbe76f4a3c7e58da3dcdc67095803f
