### ISSUE TITLE
Guidelines for External Media on Homepage Cards

### ISSUE THREAD

**Issue by thejeffreytaylor** [mozilla/protocol#95]

**Comment by alexgibson** [comment]
https://github.com/mozilla/protocol/wiki/Homepage-Cards:-External-Media-Guidelines

**Comment by thejeffreytaylor** [comment]
Raphael wants to discuss SEO implications and there will be revisions, so I'm reopening this.

**Comment by rraue** [comment]
Sorry to open this again, and not sure if this is the right place to discuss it but as you probably knew I would recommend on Youtube embeds exactly the opposite then we do in the guidelines. Plays and interactions with videos are one of the top ranking factors for both search and trends on youtube and for videosearch in google as well and we are loosing by this on of the drivers for this.

**Comment by bensternthal** [comment]
Raphael & Alex: I'd like to know more about this.. what is the rationale behind the recommendation to avoid youtube embeds whenever possible?

I am also curious what security reasons prevent other embeds from daily motion etc.

I am not saying we should do one thing or the other at this stage but I will like to better understand the thinking behind the recommendation.

Similar question for Raphael, I'd like to know from your perspective what you think.

**Comment by alexgibson** [comment]
Ok I think we need to provide a little more context in the guidelines here:

> Raphael & Alex: I'd like to know more about this.. what is the rationale behind the recommendation to avoid youtube embeds whenever possible?

We don't actually recommend to avoid YouTube whereever possible. The guidelines don't strictly say we do this, but we should reword to provide a better explaination for when we do / don't recommend YouTube.

Reasons to use a YouTube embed:

- SEO. If it's a video we expect people to search for, or have a high-draw on social media that may correlate to people downloading the product then YouTube may make sense. A good example of this may be https://www.youtube.com/watch?v=YIywpvHewc0
- We want to leverage the captioning of videos to provide translation for l10n (the auto-captioning is not very good, but for videos we control we can provide the translations I believe).

Reasons to avoid a YouTube embed:
- If the video makes little sense outside of the page where the video is shown e.g. https://assets.mozilla.net/video/firefox-home/screenshots.webm (from a user perspective this would be super confusing to see standalone on YouTube, and would probably do our brand little favours).
- User privacy. We generally avoid as many third parties as possible for privacy reasons unless there's a good reason to use one, and the big G should be no exception. If we do embed a YouTube embed video, we try and use https://www.youtube-nocookie.com.
- Web Performance & Security. Embedding a YouTube video requires loading of third party JS, which adds to page weight and is also less secure than 1st party code.

> I am also curious what security reasons prevent other embeds from daily motion etc.

Again i think we need to provide some extra context here in the guidelines, as it may seem mysterious without. Mozilla.org uses a [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) to limit the number of third party resources we are allowed to load on this site. We do this shrink the scope of third party code being able to excecute on the same pages where people download Firefox from, to try and limit the risk of [XSS exploits](https://en.wikipedia.org/wiki/Cross-site_scripting) and also to improve user privacy. There's no technical reason why we can't add daily motion to our exception list, but we should stop and ask why there is a good reason to use it instead of something else that's already on the allowed list (e.g. YouTube).

**Comment by alexgibson** [comment]
Also generally in the guidelines I think instead of saying "We cannot do X, Y, Z", we should instead provide some explaination as to how we treat third party resources in relation to CSP as outlined above. There's nothing we "cannot" do technically speaking, but we have reasons why we prefer to do X over Y.

**Comment by rraue** [comment]
I fully agree with everything Alex says and we should have these in the guidelines clearer. 

My arguments are in my post above:

- Plays and Embeds are one of the top ranking and trending factors on youtube
- Not just of the video itself but of the channel and all past videos in it
- Youtube is the second biggest search engine in the web  (without china)
- Youtube videos rank very well in normal Google search as well and links, citations, embeds are are top ranking factor there as well
- Youtube is driving around 170k desktop downloads a month right now and and is not yet highly managed (in my knowledge) so this number is already considerable and has still potential
- Videos not being general interest for at least a not too small target group should not be on youtube and therefor not a embed on our site, as its lowering genral reach of the channel. This should be part of a youtube guideline and also part of ours
- The example video of not being reasonable for youtube is imo very reasonable, youtube is full of how to do xyz videos. I learned how long to boil a egg there ;) And Youtube Suggest (autocomplete search type ins) suggests that users are actively searching in different ways for exactly such a video 
- If we have the video in several languages, and its relevant for a broader audience, we should upload them in differnet languages and embed them, we would need a workflow/system for this, because the problem Alex is describing is real
- There is nothing I could support more then caring about pageload and third party stuff on our site, but we should write this differnet so people approach us and understand the impact and not just avoid it and I think from our current copy people would just avoid it, even if it would make sense

- About security I cant talk, but concentrating on youtube as its the biggest channel seems just from a reach standpoint the right decition

**Comment by alexgibson** [comment]
Sgtm, although I have to disagree about the “how to” video. It was never made to be used in this context, has no audio track or explaination of what the video is showing, and no introduction. Our user experience bar should be higher here.

To try and sum up my thoughts, I think “defaulting to YouTube” is the wrong way to think about this. We should default to self hosted, but have a set of criteria to upgrade hosting to YouTube (SEO tank, video standards etc.)

**Comment by thejeffreytaylor** [comment]
I will be re-frosting this cake early next week.

**Comment by bensternthal** [comment]
I think we are converging on the same thing.. which is good.

It looks like we have three main channels.

https://www.youtube.com/user/Mozilla
https://www.youtube.com/user/firefoxchannel/
https://www.youtube.com/user/mozhacks

These channels, the videos have a narrative. So to Alex's point a video about screenshots could be out of place, I agree (to be fair maybe it could live in mozhacks or wherever SUMO puts their videos but for the sake of this discussion let's use it as an example that does not make sense without the context of the page it lived in). 

Some of the advantages to youtube is that.. the videos are searchable / discoverable / persistent. We often change our webpages and once we do.. generally the videos we link to if hosted on a CDN become orphaned.  I was thinking of this [video](https://www.youtube.com/watch?v=LtOGa5M8AuU), which was prominent on moz.org but now the only place it is discoverable is on youtube.

So what I am thinking is that we use a checklist like the below to decide if we youtube or selfhost.

We would selfhost if the following are all true:

- [ ] The video has meaning/impact due in large part to the moz.org page it lives on.
- [ ] If the page changes or goes away we do not care about people viewing the video.
- [ ] We do not want to leverage captioning.

Given the effort to organize our videos on youtube, I do not see a compelling reason to look at other video hosting platforms like dailymotion.
